# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'APIUnitTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for APIUnitTest
  pod 'Alamofire', '~> 4.5'

  target 'APIUnitTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'APIUnitTestUITests' do
    # Pods for testing
  end

end
